### ISSUE TITLE
A section for Arch distro users 

### ISSUE THREAD

**Issue by luzpaz** [ceremcem/build-freecad-asm3#2]
Please consider adding a build script for Arch users

Link to the Arch AUR: https://aur.archlinux.org/packages/?O=0&K=freecad

**Comment by ceremcem** [comment]
After a quick search, providing build scripts would be a nice introduction to Arch Linux for me but I regret to say that it might not happen in a short period of time.

**Comment by ceremcem** [comment]
@luzpaz  Isn't it possible to create a Debian Stretch LXC container under Arch? See [the advantages](https://github.com/ceremcem/build-freecad-asm3#advantages). Or are there any disadvantages using an LXC container to build and run an application within, in terms of 

* Performance (shouldn't be)
* Ease of install (shouldn't be)
* Disk usage (+3GB for a new install, I guess it's acceptable)
* Other

**Comment by luzpaz** [comment]
Honestly I don't know. Maybe we can get some arch folks here to join the discussion.

**Comment by Salamandar** [comment]
After searching for the "someone told me something about freecad on github" for 10 minutes, i'm here :p 
I'll read your repo Readme, and try to write a PKGBUILD. I guess this wouldn't be too difficult.
That would mean:
* Rewrite the Freecad PKGBUILD with the LinkStage3 branch
* Write a PKGBUILD for the Assembly3 tool

Am I missing something ?

**Comment by ceremcem** [comment]
Welcome :) 

> Am I missing something ?

I guess that's exactly what @luzpaz wanted. But I really wonder about how these PKGBUILD scripts can be generated within this repo.

**Comment by ceremcem** [comment]
> if that's what you're talking about

Yes, that was my first guess, but using the existing scripts sounds quite better.

**Comment by Salamandar** [comment]
Well, after thinking about it, as the existing scripts are not structured enough (PKGBUILD splits build, package and install), maybe you could use the PKGBUILDs if you want.

In any case, I'll upload them on AUR for native build.

**Comment by Salamandar** [comment]
Here is the Workbench PKGBUILD : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freecad-assembly3-git

**Comment by luzpaz** [comment]
> Here is the Workbench PKGBUILD : aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freecad-assembly3-git


https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freecad-assembly3-git#n6  
Should be version **0.18dev**

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freecad-assembly3-git#n47  
Why do you exclude solvespace from the rsync ?

**Comment by Salamandar** [comment]
>  Should be version **0.18dev**

Yeah, that's on my next commit xD

>  Why do you exclude solvespace from the rsync ?

Well, this directory only contains sources/builddir of slvs, the corresponding library was copied into py_slvs, right ?

**Comment by Salamandar** [comment]
The Freecad build system is very broken. It does not detect Netgen if I dont specify the paths, and it does not detect QtWebkit (but it still tries to build DownloadManager)…

**Comment by ceremcem** [comment]
> The Freecad build system is very broken 

There were lots of issues I had too. It gets a very time consuming task to make the build procedure work flawlessly.

**Comment by Salamandar** [comment]
Yeah, CMake easily becomes awful to work with for big projects.

**Comment by ceremcem** [comment]
Actually, that's the reason why I strongly suggest using containers. One build process rules them all.

**Comment by luzpaz** [comment]
I think QtWebkit is not enabled on Debian (due to security concerns) and that is the reason it carries over to other Linux builds. I may be wrong.

**Comment by luzpaz** [comment]
@kkremitzki care to weigh in on netgen detection in FC ?

**Comment by Salamandar** [comment]
@ceremcem Yeah, but then you don't need Archlinux-specific scripts ;)

**Comment by Salamandar** [comment]
`../src/Gui/View3DInventorViewer.cpp:2825:49: error: « virtual void SoCamera::viewBoundingBox(const SbBox3f&, float, float) » est protégé dans ce contexte`
Soo… Freecad is broken for now.
I'll upload the PKGBUILD, but it does not work yet.

**Comment by Salamandar** [comment]
https://aur.archlinux.org/packages/freecad-linkstage3-git/

**Comment by Salamandar** [comment]
![capture du 2018-09-21 17-26-16](https://user-images.githubusercontent.com/6552989/45890537-82786200-bdc3-11e8-9da0-6ab32d1820ba.png)
Well, I had to fix the error (I just commented `src/Gui/View3DInventorViewer.cpp:2825`), and here it is.

**Comment by ceremcem** [comment]
@luzpaz can we close the issue?
