### ISSUE TITLE
issue with running on Fedora

### ISSUE THREAD

**Issue by HaasNL2** [ceremcem/build-freecad-asm3#20]
I fixed the apt-get in the script but the debian keyring doesn't install. It say no match.
![image](https://user-images.githubusercontent.com/29804962/112944273-e4ec0f00-9132-11eb-9a5c-f17fd4e22904.png)

**Comment by ceremcem** [comment]
I think you also don't have LXC installed (last lines say `lxc-create command not found`). First install LXC, then try to create a Debian container manually (see [this](https://github.com/ceremcem/build-freecad-asm3/blob/master/manual-install.md#1-setup-a-debian-lxc-container)): 

```
sudo lxc-create -n fc -t debian -- -r buster --packages nano sudo git
```

Let's first see if it succeeds or not.

**Comment by christian-nils** [comment]
I am trying to do the same on Fedora 34. Here is the error I get with your command:

```
lxc-create: fc: utils.c: get_template_path: 884 No such file or directory - bad template: debian
lxc-create: fc: lxccontainer.c: do_lxcapi_create: 1786 Unknown template "debian"
lxc-create: fc: tools/lxc_create.c: main: 319 Failed to create container fc
```

**Comment by ceremcem** [comment]
@christian-nils It looks like a Fedora+LXC issue. Let's resolve it first. In Debian, there is a separate package for templates: 

```console
$ sudo apt-cache search lxc-templates
lxc-templates - Linux Containers userspace tools (templates)
```

Do you have such a package? If yes, can you try to install it? Someone else says "you need to install `debootstrap`": https://bugs.mageia.org/show_bug.cgi?id=16475#c1

**Comment by ceremcem** [comment]
I'm going to close this issue as it's stale. Please file another issue if the problem persists.
