### ISSUE TITLE
Re-build

### ISSUE THREAD

**Issue by macdroid53** [ceremcem/build-freecad-asm3#22]
So, today I did a git pull on my RT source.

Went off to my build-freecad-asm3/tools directory and issued:

```
./auto.sh --freecad-src ~/freecadL3-source
```

And got:

```
Skipping setup: Container already exists at /var/lib/lxc/fc.

Run FreeCAD anytime with:

    ./freecad.sh

```

**Comment by ceremcem** [comment]
What is your actual purpose? Do you want to update FreeCAD by pulling new commits and re-compiling? If so, you need to issue the following command: 

```
./update-fc.sh
```

This command will:
* Pull new commits into the FreeCAD clone at `/var/lib/lxc/fc/rootfs/home/aea/FreeCAD`
* Recompile the source code inside the container

**Comment by ceremcem** [comment]
Your first clone (at `~/freecadL3-source`) is [just copied into the container](https://github.com/ceremcem/build-freecad-asm3/blob/27fdffe5769ded08ad8a726beaff7a4dfb5c7b59/tools/auto.sh#L145) while setting up the container. After you succesfully create the container and build FreeCAD, you can free to delete `~/freecadL3-source`, because it's never used again.

**Comment by macdroid53** [comment]
I have the source in ~/freecadL3-source.
I cd'd to that directory and issues: git pull
This gets the latest changes to the source.
(Just noted what I did...)

I then want to build the latest source.

Am I to understand that ./update.sh accomplishes this updating the source in the container?

If so I unwisely used the lxc command line to remove the container and am in the process of building the container, again, from scratch with ./auto.sh.

Oops, I guess.

**Comment by ceremcem** [comment]
> If so I unwisely used the lxc command line to remove the container and am in the process of building the container, again, from scratch with ./auto.sh.

That was very unfortunate... So yes, you need to re-create the container and so on. After that, use `./update.sh` whenever you want to update your FreeCAD binary.

**Comment by ceremcem** [comment]
FYI: I just renamed the `./auto.sh` to `./setup-all.sh` to reduce the confusion about the purpose of that script and added an appropriate updating procedure to the README.

**Comment by macdroid53** [comment]
Thanks for the explanations.

I admit I'm not savvy about what LXC does...first I'd heard of it was your use here. Hence my bumbling around in the LXC man pages and removing the container.

I actually read the auto.sh and update scripts and didn't put the whole thing together.

**Comment by ceremcem** [comment]
Sorry for missing information. Sometimes some information seems to be obvious while it's not. 

Please consider closing the issue whenever you satisfied with the answers here.

**Comment by macdroid53** [comment]
> Sorry for missing information. Sometimes some information seems to be obvious while it's not.

Indeed, I always try to assume the lowest common denominator when do documentation, then those who find it obvious can ignore what they already know...and even then I miss stuff that the consumer doesn't find. 

> 
> Please consider closing the issue whenever you satisfied with the answers here.

Done. Thanks again!
